root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /index
        permanent: true

index:
    path: /index
    controller: App\Controller\DefaultController::index

bus:
    path: /bus
    controller: App\Controller\DefaultController::bus

bus_mini:
    path: /bus/mini
    controller: App\Controller\DefaultController::bus_mini

bus_simple:
    path: /bus/classic
    controller: App\Controller\DefaultController::bus_simple

bus_double:
    path: /bus/double
    controller: App\Controller\DefaultController::bus_double

bus_super:
    path: /bus/super_double
    controller: App\Controller\DefaultController::bus_super

program:
    path: /program
    controller: App\Controller\DefaultController::program

pricing:
    path: /pricing
    controller: App\Controller\DefaultController::pricing

options:
    path: /options
    controller: App\Controller\DefaultController::options

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

