index:
    path: /
    controller: App\Controller\DefaultController::index

bus:
    path: /bus
    controller: App\Controller\DefaultController::bus

bus_mini:
    path: /bus/mini
    controller: App\Controller\DefaultController::bus_mini

bus_middle:
    path: /bus/middle
    controller: App\Controller\DefaultController::bus_middle

bus_classic:
    path: /bus/classique
    controller: App\Controller\DefaultController::bus_classic

bus_double:
    path: /bus/double
    controller: App\Controller\DefaultController::bus_double

bus_super:
    path: /bus/super_double
    controller: App\Controller\DefaultController::bus_super

program:
    path: /soirée
    controller: App\Controller\DefaultController::program

pricing:
    path: /prix
    controller: App\Controller\DefaultController::pricing

options:
    path: /options
    controller: App\Controller\DefaultController::options

booking:
    path: /réservation
    controller: App\Controller\DefaultController::booking

old_index:
    path: /index
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true

old_booking:
    path: /booking
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /réservation
        permanent: true

old_bus_mini:
    path: /bus_mini
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /bus/mini
        permanent: true

old_bus_classic:
    path: /bus_classic
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /bus/classique
        permanent: true

old_bus_double:
    path: /bus_double
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /bus/double
        permanent: true

old_bus_super:
    path: /bus_super
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /bus/super_double
        permanent: true

old_contact:
    path: /contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /réservation
        permanent: true

old_pricing:
    path: /pricing
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /prix
        permanent: true

old_program:
    path: /program
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /soirée
        permanent: true